live_config_reload = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = false
opacity = 0.9
startup_mode = "Maximized"
