#!/usr/bin/env bash
# Enable bash's unofficial strict mode
GITROOT=$(git rev-parse --show-toplevel)
# shellcheck disable=SC1090
. "${GITROOT}"/lib/strict-mode
strictMode
# Enabling utils
# shellcheck disable=SC1090
. "${GITROOT}"/lib/utils


function test_arrays() {
  # does not consider namerefs, see https://github.com/koalaman/shellcheck/issues/817
  # shellcheck disable=SC2034
  declare -a arr=(a b c 'd e' f g) sub_arr=(b c) not_sub_arr=(g h)
  array_contains 'a b' "${arr[@]}" && echo yes || echo no      # Should be no
  array_contains 'd e' "${arr[@]}" && echo yes || echo no      # Should be yes
  is_subarray_in_array arr sub_arr  && echo yes || echo no     # Should be yes
  is_subarray_in_array arr not_sub_arr  && echo yes || echo no # Should be no
}

test_arrays

function test_latest_tag() {
  local repo1="https://github.com/JetBrains/kotlin"
  local repo2="https://github.com/asdf-vm/asdf.git"
  echo "getting tags for ${repo1}"
  declare -a tags_from_repo1 tags_from_repo2
  mapfile -t tags_from_repo1 < <(get_git_tags "${repo1}")
  echo "tags from repo1 are: ${tags_from_repo1[*]}"
  echo "latest tag from repo1 is: ${tags_from_repo1[-1]}"
  echo "getting tags for ${repo2}"
  mapfile -t tags_from_repo2 < <(get_git_tags "${repo2}")
  echo "tags from repo2 are: ${tags_from_repo2[*]}"
  echo "latest tag from repo2 is: ${tags_from_repo2[-1]}"
}

#test_latest_tag
