[tools]
go = "1.27.1"
groovy = "2.4.12"
java = "temurin-25.0.4+101.0.LTS"
kotlin = "2.4.20"
lua = "5.5.1"
maven = "3.6.3"
node = "24.21.0"
opam = "2.6.0"
python = "3.13.15"
ruby = "4.0.7"
rust = "1.98.1"
gradle = "9.8.0"
terraform = "1.15.8"
pulumi = "3.264.0"
kubectl = "1.37.1"
kompose = "1.38.0"
helm = "4.3.0"
kustomize = "5.8.1"
helm-docs = "1.14.2"
helm-ct = "3.14.0"
1password-cli = "2.24.0"
rclone = "1.75.1"
tflint = "0.64.0"
sbt = "2.0.9"
uv = "0.12.19"
krew = "0.5.0"
"vfox:mise-plugins/vfox-dotnet" = "10.0.302"
opencode = "1.18.32"

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "java", "node"]
