[tools]
go = "1.26.5"
groovy = "2.4.12"
java = "temurin-25.0.4+7.0.LTS"
kotlin = "2.4.10"
lua = "5.5.1"
maven = "3.6.3"
node = "24.19.0"
opam = "2.5.2"
python = "3.13.15"
ruby = "4.0.6"
rust = "1.97.1"
gradle = "9.7.0"
terraform = "1.15.8"
pulumi = "3.256.0"
kubectl = "1.36.3"
kompose = "1.38.0"
helm = "4.2.3"
kustomize = "5.8.1"
helm-docs = "1.14.2"
helm-ct = "3.14.0"
1password-cli = "2.24.0"
rclone = "1.75.0"
tflint = "0.64.0"
sbt = "2.0.6"
uv = "0.12.3"
krew = "0.5.0"
"vfox:mise-plugins/vfox-dotnet" = "10.0.302"

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "java", "node"]
