#!/usr/bin/env bash
# Enable bash's unofficial strict mode
GITROOT=$(git rev-parse --show-toplevel)
# shellcheck disable=SC1091
. "${GITROOT}"/lib/strict-mode
strictMode
# Enabling utils
# shellcheck disable=SC1091
. "${GITROOT}"/lib/utils


function are_basics_installed() {
  local ASK="${1:-'y'}"
  declare -a UBUNTU_BASICS BREW_BASICS
  UBUNTU_BASICS=('apt-file'
    'apt-transport-https'
    'build-essential'
    'curl'
    'dirmngr'
    'file'
    'gawk'
    'gnome-tweaks'
    'gnupg'
    'gnutls-bin'
    'inetutils-tools'
    'libxml2-utils'
    'lsb-release'
    'procps'
    'python3-keyring'
    'software-properties-common'
    'wget'
    'xclip'
    'xz-utils'
    'zlib1g-dev')
  BREW_BASICS=('asciidoc'
   'awscli'
   'fontconfig'
   'gcc'
   'git'
   'git-filter-repo'
   'jc'
   'jless'
   'jq'
   'mackup'
   'oh-my-posh'
   'parallel'
   'pssh'
   'saml2aws'
   'tree'
   'vim'
   'yq')
  msg_info 'Will run apt update'
  sudo apt update
  msg_info 'Will try to install Ubuntu basics'
  install_if_not_installed 'apt' "${ASK}" "${UBUNTU_BASICS[@]}"
  msg_info 'Will try to install brew if not installed'
  is_brew_installed "${ASK}"
  install_if_not_installed 'brew' "${ASK}" "${BREW_BASICS[@]}"
}

function is_asdf_installed() {
  local ASK="${1:-'y'}"
  if [[ ! -e "${HOME}/.asdf/asdf.sh" ]] || [[ ! -e "$(get_brew_location)" ]]; then
    # Ubuntu 18.04 `apt install -y libncurses-dev libxslt-dev` gives the output below
    # Note, selecting 'libncurses5-dev' instead of 'libncurses-dev'
    # Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
    declare -a ASDF_DEPS=('autoconf'
      'automake'
      'libbz2-dev'
      'libffi-dev'
      'libncurses5-dev'
      'libreadline-dev'
      'libsqlite3-dev'
      'libssl-dev'
      'libtool'
      'libxslt1-dev'
      'libyaml-dev'
      'unixodbc-dev'
      'unzip')
    are_basics_installed "${ASK}"
    msg_info 'Will try to install asdf dependencies'
    install_if_not_installed 'apt' "${ASK}" "${ASDF_DEPS[@]}"
    msg_info 'Will try to install asdf using git'
    git_install_asdf "${ASK}"
  fi
  source_asdf
}
