# Ubuntu only aliases and functions
# ricdros' custom aliases
#alias ls='ls --color=auto'
alias apt-search='sudo apt search'
alias upgrade="sudo apt update && sudo apt dist-upgrade"
alias upinstall="sudo apt update && sudo apt install"
alias install="sudo apt install"
alias showversion="neofetch"
alias bw='OPENSSL_CONF=/dev/null bw'
# http://www.briandolhansky.com/blog/2014/8/5/linux-snippets-using-xclip-to-pipe-to-the-system-clipboard
alias xclip='xclip -selection c'

# Add key to ssh-agent
function addkeys () {
  declare -a SSH_KEYS=()
  for file in ~/.ssh/id_*; do
    if grep -q 'private key'; then
      SSH_KEYS+=("${file}")
    fi
  done
  if ! pgrep -u "$(id -u)" 'ssh-agent' &> /dev/null; then
    eval "$(ssh-agent -s)"
  fi
  if [[ -z "${SSH_AUTH_SOCK}" ]]; then
    SSH_AUTH_SOCK="$(ls /tmp/ssh*/agent.*)"
  fi
  export SSH_AUTH_SOCK
  for KEY in "${SSH_KEYS[@]}"; do
    if ssh-add -L | grep -q "$(awk '{ print $2 }' "${KEY}".pub)" &> /dev/null; then
      msg_info "You already have ${KEY} in ssh-add"
    else
      msg_info "You already have a ssh-agent session running, we will now add ${KEY}"
      ssh-add "${KEY}"
    fi
  done
}

# Clean your environment from ssh-agent stuff
function cleansshagent () {
  unset SSH_AUTH_SOCK && \
  unset SSH_AGENT_PID && \
  echo 'list ssh-agent PIDs before pkill' && \
  pgrep -u "$(id -u)" 'ssh-agent' && \
  pkill -u "$(id -u)" 'ssh-agent' && \
  echo 'list ssh-agent PIDs after pkill' && \
  pgrep -u "$(id -u)" 'ssh-agent'
}

function aptlistinrepo() {
  local REPO="${1:-ppa.launchpad}"
  grep ^Package \
    /var/lib/apt/lists/"${REPO}"*_Packages | awk '{print $2}' | sort -u
}
