eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# `asdf` is now managed by homebrew
# shellcheck disable=SC1090
. <(asdf completion bash)
# Hook direnv into your shell.
# shellcheck disable=SC1091
. "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/bashrc"

# Go specific env vars
GOPATH="${HOME}/src/gopath"
GOROOT="$(asdf where golang)/go"
export GOPATH GOROOT

# Java specific env vars
JDK_HOME="$(asdf where java)"
JAVA_HOME="$(asdf where java)/jre"
export JDK_HOME JAVA_HOME

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

for file in "$(brew --prefix)"/etc/bash_completion.d/*; do
  . "${file}"
done

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    # shellcheck disable=SC1091
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    # shellcheck disable=SC1091
    . /etc/bash_completion
  fi
fi

# Mojo specific env vars
export MODULAR_HOME="${HOME}/.modular"

export PATH="${HOME}/.modular/pkg/packages.modular.com_mojo/bin:${PATH}:${HOME}/src/gopath/bin:${HOME}/.local/bin:${HOME}/bin:/snap/bin"
