#!/usr/bin/env bash
# Enable bash's unofficial strict mode
GITROOT=$(git rev-parse --show-toplevel)
# shellcheck disable=SC1091
. "${GITROOT}"/lib/strict-mode
strictMode
# Enabling utils
# shellcheck disable=SC1091
. "${GITROOT}"/lib/utils


function are_basics_installed() {
  local ASK="${1:-'y'}"
  # `awscli` https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html
  declare -a BREW_BASICS=(
    'actionlint'
    'asdf'
    'awscli'
    'bash'
    'coreutils'
    'curl'
    'gawk'
    'git'
    'git-filter-repo'
    'gnupg'
    'gnutls'
    'gnu-sed'
    'inetutils'
    'jc'
    'jless'
    'jq'
    'bitwarden-cli'
    'mackup'
    'mas'
    'oh-my-posh'
    'parallel'
    'pssh'
    'saml2aws'
    'tealdeer'
    'tree'
    'neovim'
    'stylua'
    'wget'
    'xz'
    'yq')
  msg_info 'Will try to install brew if not installed'
  is_brew_installed "${ASK}"
  msg_info 'Will try to install basic packages with brew'
  install_if_not_installed 'brew' "${ASK}" "${BREW_BASICS[@]}"
}

function is_asdf_installed() {
  local ASK="${1:-'y'}"
  if ! command -v asdf &> /dev/null || ! command -v brew &> /dev/null; then
    declare -a ASDF_DEPS=('autoconf'
      'automake'
      'coreutils'
      'gcc'
      'libtool'
      'libxslt'
      'libyaml'
      'openssl'
      'make'
      'readline'
      'unixodbc'
      'unzip')
    msg_info 'Will try to install brew if not installed'
    are_basics_installed "${ASK}"
    msg_info 'Will try to install asdf dependencies'
    install_if_not_installed 'brew' "${ASK}" "${ASDF_DEPS[@]}"
    msg_info 'Will try to install asdf using git'
    source_asdf
  fi
}
