# MacOS only aliases and functions
# ricdros' custom aliases
#alias ls='ls -G'
alias ldd='otool -L'
alias update='softwareupdate -l'

function watch () {
  local SECONDS=${1}
  shift
  declare -a COMMANDS=()
  # https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u
  COMMANDS=("${@+"${@}"}")
  while true ; do
    clear && echo "Watching ${COMMANDS[*]} every ${SECONDS} seconds" && "${COMMANDS[@]+"${COMMANDS[@]}"}" && sleep "${SECONDS}"
  done
}

function getent() {
  # Trying to make dscacheutil like getent
  # in macOS `man dscacheutil`
  # in Linux `man getent`
  local CATEGORY=${1:-host}
  local QUERY_KEY=${3:-name}
  local QUERY_VALUE=${2}
  dscacheutil -q "${CATEGORY}" -a "${QUERY_KEY}" "${QUERY_VALUE}"
}

function cleancolima() {
  colima stop
  rm -rf ~/.colima ~/.lima ~/Library/Caches/colima ~/Library/Caches/lima
}
