if [[ "$(uname -m)" == 'arm64' ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  eval "$(/usr/local/bin/brew shellenv)"
fi

# Homebrew's Bash completion stuff
if [ -f "$(brew --prefix)"/etc/bash_completion ]; then
  # shellcheck disable=SC1091
  source "$(brew --prefix)"/etc/bash_completion
fi

# Update PATH
export PATH="$(brew --prefix)/opt/curl/bin:${PATH}:${HOME}/src/gopath/bin:${HOME}/bin"

# Source: https://iterm2.com/documentation-shell-integration.html
# shellcheck disable=SC1091
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Added by Antigravity
export PATH="/Users/Ricardo.Rosales/.antigravity/antigravity/bin:$PATH"
