# Homebrew's Bash completion stuff
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  source $(brew --prefix)/etc/bash_completion
fi

# Update PATH
export PATH="${PATH}:$(brew --prefix)/sbin:$(brew --prefix)/opt/libarchive/bin:$(brew --prefix)/opt/gettext/bin:${HOME}/src/gopath/bin:${HOME}/bin"

# Source: https://iterm2.com/documentation-shell-integration.html
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
